name: Add to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
    - name: Add to Project
      uses: actions/add-to-project@v1
      with:
        project_name: My Project
        column_name: To do
        issue_number: ${{ github.event.issue.number }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.label.name == 'bug'
